---
- hosts: all
  become: yes
 # tasks:
 #   - name: install apache2
 #     apt: name=apache2 update_cache=yes state=latest

#  handlers:
#    - name: restart apache2
#     service: name=apache2 state=restarted
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]
    - name: Install LAMP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: ['apache2', 'mysql-server', 'python-pymysql', 'python3-pymysql', 'python-apt', 'python3-apt', 'php', 'php-mysql', 'libapache2-mod-php' ]
 # MySQL Configuration
    - name: Sets the root password
      mysql_user:
        name: root
        password: 'Google.com@123'
        check_implicit_admin=yes
        priv="*.*:ALL,GRANT"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        with_items:
           - "{{ current_hostname.stdout }}"        
           - "127.0.0.1"
           - "%"
           - "localhost"

    - name: Removes all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "Google.com@123"

    - name: Removes the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "Google.com@123" 

  # PHP Info Page
    - name: Sets Up PHP Info Page
      template:
        src: "vagrant_site/info.php"
        dest: "/var/www/html/info.php"

    - name: Restarting Apache2
      command: '/etc/init.d/apache2 restart'              