---
- hosts: all
  become: yes
  tasks:
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]
    - name: Install LAMP Packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: ['apache2', 'mysql-server', 'python-pymysql', 'python3-pymysql', 'python-apt', 'python3-apt', 'php', 'php-mysql', 'libapache2-mod-php' ]
 
  # MySQL Configuration
    - name: Sets the root password
      mysql_user:
        name: root
        password: 'Google.com@123'
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Removes all anonymous user accounts
      mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: "Google.com@123"

    - name: Removes the MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "Google.com@123" 
    
    - name: Create Php Files
      copy:
        dest: "/var/www/html/info.php"
        content: |
           <?php phpinfo(); ?>

    - name: Restart Apache
      service:
        name: apache2
                                          